run-name: ${{ github.repository }} Build

on:
  pull_request:
    branches:
      - '*'
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.19
      - uses: actions/setup-node@v4.0.3
        with:
          cache: npm
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          CI: true

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.19
      - uses: actions/setup-node@v4.0.3
        with:
          cache: npm
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Check code format
        run: npm run format:check
  
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.19
      - uses: actions/setup-node@v4.0.3
        with:
          cache: npm
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint:check
  

