run-name: ${{ github.repository }} Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  release:
    permissions:
      contents: write
      packages: write
    concurrency:
      # Only one release job at a time. Strictly sequential.
      group: release
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      node-version: ${{ steps.node-version.outputs.node-version }}
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.19
      - uses: actions/setup-node@v4.0.3
        with:
          cache: npm
          node-version: lts/*
      - run: npm clean-install
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  success:
    runs-on: ubuntu-latest
    needs:
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
